// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"example.com/xxx/user-service/internal/biz"
	"example.com/xxx/user-service/internal/conf"
	"example.com/xxx/user-service/internal/data"
	"example.com/xxx/user-service/internal/pkg/casbin"
	"example.com/xxx/user-service/internal/pkg/jwt"
	"example.com/xxx/user-service/internal/server"
	"example.com/xxx/user-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"go.uber.org/zap"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger *zap.Logger) (*kratos.App, func(), error) {
	jwtHelper := xjwt.NewJwtHelper(bootstrap)
	db := data.NewDb(bootstrap)
	enforcer := xcasbin.NewCasbin(db, bootstrap)
	dataData, cleanup, err := data.NewData(bootstrap, db, enforcer, jwtHelper)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData)
	userUseCase := biz.NewUserUseCase(userRepo, jwtHelper, enforcer)
	userService := service.NewUserService(userUseCase)
	roleRepo := data.NewRoleRepo(dataData)
	rolePermissionRepo := data.NewRolePermissionRepo(dataData)
	permissionRepo := data.NewPermissionRepo(dataData)
	roleUseCase := biz.NewRoleUseCase(roleRepo, rolePermissionRepo, permissionRepo, enforcer, userRepo)
	roleService := service.NewRoleService(roleUseCase)
	permissionUseCase := biz.NewPermissionUseCase(permissionRepo, enforcer)
	permissionService := service.NewPermissionService(permissionUseCase)
	grpcServer := server.NewGRPCServer(bootstrap, jwtHelper, enforcer, userService, roleService, permissionService)
	registrar := data.NewRegistrar(bootstrap)
	app := newApp(grpcServer, logger, registrar)
	return app, func() {
		cleanup()
	}, nil
}
