// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.4
// source: asset/v1/demo.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDemoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDemoRequest) Reset() {
	*x = CreateDemoRequest{}
	mi := &file_asset_v1_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDemoRequest) ProtoMessage() {}

func (x *CreateDemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asset_v1_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDemoRequest.ProtoReflect.Descriptor instead.
func (*CreateDemoRequest) Descriptor() ([]byte, []int) {
	return file_asset_v1_demo_proto_rawDescGZIP(), []int{0}
}

type CreateDemoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDemoReply) Reset() {
	*x = CreateDemoReply{}
	mi := &file_asset_v1_demo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDemoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDemoReply) ProtoMessage() {}

func (x *CreateDemoReply) ProtoReflect() protoreflect.Message {
	mi := &file_asset_v1_demo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDemoReply.ProtoReflect.Descriptor instead.
func (*CreateDemoReply) Descriptor() ([]byte, []int) {
	return file_asset_v1_demo_proto_rawDescGZIP(), []int{1}
}

type UpdateDemoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDemoRequest) Reset() {
	*x = UpdateDemoRequest{}
	mi := &file_asset_v1_demo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDemoRequest) ProtoMessage() {}

func (x *UpdateDemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asset_v1_demo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDemoRequest.ProtoReflect.Descriptor instead.
func (*UpdateDemoRequest) Descriptor() ([]byte, []int) {
	return file_asset_v1_demo_proto_rawDescGZIP(), []int{2}
}

type UpdateDemoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDemoReply) Reset() {
	*x = UpdateDemoReply{}
	mi := &file_asset_v1_demo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDemoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDemoReply) ProtoMessage() {}

func (x *UpdateDemoReply) ProtoReflect() protoreflect.Message {
	mi := &file_asset_v1_demo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDemoReply.ProtoReflect.Descriptor instead.
func (*UpdateDemoReply) Descriptor() ([]byte, []int) {
	return file_asset_v1_demo_proto_rawDescGZIP(), []int{3}
}

type DeleteDemoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDemoRequest) Reset() {
	*x = DeleteDemoRequest{}
	mi := &file_asset_v1_demo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDemoRequest) ProtoMessage() {}

func (x *DeleteDemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asset_v1_demo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDemoRequest.ProtoReflect.Descriptor instead.
func (*DeleteDemoRequest) Descriptor() ([]byte, []int) {
	return file_asset_v1_demo_proto_rawDescGZIP(), []int{4}
}

type DeleteDemoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDemoReply) Reset() {
	*x = DeleteDemoReply{}
	mi := &file_asset_v1_demo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDemoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDemoReply) ProtoMessage() {}

func (x *DeleteDemoReply) ProtoReflect() protoreflect.Message {
	mi := &file_asset_v1_demo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDemoReply.ProtoReflect.Descriptor instead.
func (*DeleteDemoReply) Descriptor() ([]byte, []int) {
	return file_asset_v1_demo_proto_rawDescGZIP(), []int{5}
}

type GetDemoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDemoRequest) Reset() {
	*x = GetDemoRequest{}
	mi := &file_asset_v1_demo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDemoRequest) ProtoMessage() {}

func (x *GetDemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asset_v1_demo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDemoRequest.ProtoReflect.Descriptor instead.
func (*GetDemoRequest) Descriptor() ([]byte, []int) {
	return file_asset_v1_demo_proto_rawDescGZIP(), []int{6}
}

type GetDemoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDemoReply) Reset() {
	*x = GetDemoReply{}
	mi := &file_asset_v1_demo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDemoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDemoReply) ProtoMessage() {}

func (x *GetDemoReply) ProtoReflect() protoreflect.Message {
	mi := &file_asset_v1_demo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDemoReply.ProtoReflect.Descriptor instead.
func (*GetDemoReply) Descriptor() ([]byte, []int) {
	return file_asset_v1_demo_proto_rawDescGZIP(), []int{7}
}

type ListDemoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDemoRequest) Reset() {
	*x = ListDemoRequest{}
	mi := &file_asset_v1_demo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDemoRequest) ProtoMessage() {}

func (x *ListDemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asset_v1_demo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDemoRequest.ProtoReflect.Descriptor instead.
func (*ListDemoRequest) Descriptor() ([]byte, []int) {
	return file_asset_v1_demo_proto_rawDescGZIP(), []int{8}
}

type ListDemoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDemoReply) Reset() {
	*x = ListDemoReply{}
	mi := &file_asset_v1_demo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDemoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDemoReply) ProtoMessage() {}

func (x *ListDemoReply) ProtoReflect() protoreflect.Message {
	mi := &file_asset_v1_demo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDemoReply.ProtoReflect.Descriptor instead.
func (*ListDemoReply) Descriptor() ([]byte, []int) {
	return file_asset_v1_demo_proto_rawDescGZIP(), []int{9}
}

var File_asset_v1_demo_proto protoreflect.FileDescriptor

const file_asset_v1_demo_proto_rawDesc = "" +
	"\n" +
	"\x13asset/v1/demo.proto\x12\fapi.asset.v1\"\x13\n" +
	"\x11CreateDemoRequest\"\x11\n" +
	"\x0fCreateDemoReply\"\x13\n" +
	"\x11UpdateDemoRequest\"\x11\n" +
	"\x0fUpdateDemoReply\"\x13\n" +
	"\x11DeleteDemoRequest\"\x11\n" +
	"\x0fDeleteDemoReply\"\x10\n" +
	"\x0eGetDemoRequest\"\x0e\n" +
	"\fGetDemoReply\"\x11\n" +
	"\x0fListDemoRequest\"\x0f\n" +
	"\rListDemoReply2\xfd\x02\n" +
	"\x04Demo\x12L\n" +
	"\n" +
	"CreateDemo\x12\x1f.api.asset.v1.CreateDemoRequest\x1a\x1d.api.asset.v1.CreateDemoReply\x12L\n" +
	"\n" +
	"UpdateDemo\x12\x1f.api.asset.v1.UpdateDemoRequest\x1a\x1d.api.asset.v1.UpdateDemoReply\x12L\n" +
	"\n" +
	"DeleteDemo\x12\x1f.api.asset.v1.DeleteDemoRequest\x1a\x1d.api.asset.v1.DeleteDemoReply\x12C\n" +
	"\aGetDemo\x12\x1c.api.asset.v1.GetDemoRequest\x1a\x1a.api.asset.v1.GetDemoReply\x12F\n" +
	"\bListDemo\x12\x1d.api.asset.v1.ListDemoRequest\x1a\x1b.api.asset.v1.ListDemoReplyB?\n" +
	"\fapi.asset.v1P\x01Z-example.com/xxx/asset-service/api/asset/v1;v1b\x06proto3"

var (
	file_asset_v1_demo_proto_rawDescOnce sync.Once
	file_asset_v1_demo_proto_rawDescData []byte
)

func file_asset_v1_demo_proto_rawDescGZIP() []byte {
	file_asset_v1_demo_proto_rawDescOnce.Do(func() {
		file_asset_v1_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_asset_v1_demo_proto_rawDesc), len(file_asset_v1_demo_proto_rawDesc)))
	})
	return file_asset_v1_demo_proto_rawDescData
}

var file_asset_v1_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_asset_v1_demo_proto_goTypes = []any{
	(*CreateDemoRequest)(nil), // 0: api.asset.v1.CreateDemoRequest
	(*CreateDemoReply)(nil),   // 1: api.asset.v1.CreateDemoReply
	(*UpdateDemoRequest)(nil), // 2: api.asset.v1.UpdateDemoRequest
	(*UpdateDemoReply)(nil),   // 3: api.asset.v1.UpdateDemoReply
	(*DeleteDemoRequest)(nil), // 4: api.asset.v1.DeleteDemoRequest
	(*DeleteDemoReply)(nil),   // 5: api.asset.v1.DeleteDemoReply
	(*GetDemoRequest)(nil),    // 6: api.asset.v1.GetDemoRequest
	(*GetDemoReply)(nil),      // 7: api.asset.v1.GetDemoReply
	(*ListDemoRequest)(nil),   // 8: api.asset.v1.ListDemoRequest
	(*ListDemoReply)(nil),     // 9: api.asset.v1.ListDemoReply
}
var file_asset_v1_demo_proto_depIdxs = []int32{
	0, // 0: api.asset.v1.Demo.CreateDemo:input_type -> api.asset.v1.CreateDemoRequest
	2, // 1: api.asset.v1.Demo.UpdateDemo:input_type -> api.asset.v1.UpdateDemoRequest
	4, // 2: api.asset.v1.Demo.DeleteDemo:input_type -> api.asset.v1.DeleteDemoRequest
	6, // 3: api.asset.v1.Demo.GetDemo:input_type -> api.asset.v1.GetDemoRequest
	8, // 4: api.asset.v1.Demo.ListDemo:input_type -> api.asset.v1.ListDemoRequest
	1, // 5: api.asset.v1.Demo.CreateDemo:output_type -> api.asset.v1.CreateDemoReply
	3, // 6: api.asset.v1.Demo.UpdateDemo:output_type -> api.asset.v1.UpdateDemoReply
	5, // 7: api.asset.v1.Demo.DeleteDemo:output_type -> api.asset.v1.DeleteDemoReply
	7, // 8: api.asset.v1.Demo.GetDemo:output_type -> api.asset.v1.GetDemoReply
	9, // 9: api.asset.v1.Demo.ListDemo:output_type -> api.asset.v1.ListDemoReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_asset_v1_demo_proto_init() }
func file_asset_v1_demo_proto_init() {
	if File_asset_v1_demo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_asset_v1_demo_proto_rawDesc), len(file_asset_v1_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_asset_v1_demo_proto_goTypes,
		DependencyIndexes: file_asset_v1_demo_proto_depIdxs,
		MessageInfos:      file_asset_v1_demo_proto_msgTypes,
	}.Build()
	File_asset_v1_demo_proto = out.File
	file_asset_v1_demo_proto_goTypes = nil
	file_asset_v1_demo_proto_depIdxs = nil
}
