// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.4
// source: interface/v1/demo.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNo        int64                  `protobuf:"varint,1,opt,name=pageNo,proto3" json:"pageNo,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Sort          string                 `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Direction     string                 `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	RoleCode      string                 `protobuf:"bytes,5,opt,name=roleCode,proto3" json:"roleCode,omitempty"`
	RoleName      string                 `protobuf:"bytes,6,opt,name=roleName,proto3" json:"roleName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleListRequest) Reset() {
	*x = RoleListRequest{}
	mi := &file_interface_v1_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleListRequest) ProtoMessage() {}

func (x *RoleListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interface_v1_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleListRequest.ProtoReflect.Descriptor instead.
func (*RoleListRequest) Descriptor() ([]byte, []int) {
	return file_interface_v1_demo_proto_rawDescGZIP(), []int{0}
}

func (x *RoleListRequest) GetPageNo() int64 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *RoleListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *RoleListRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *RoleListRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *RoleListRequest) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

func (x *RoleListRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type RoleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleCode      string                 `protobuf:"bytes,2,opt,name=roleCode,proto3" json:"roleCode,omitempty"`
	RoleName      string                 `protobuf:"bytes,3,opt,name=roleName,proto3" json:"roleName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleReply) Reset() {
	*x = RoleReply{}
	mi := &file_interface_v1_demo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleReply) ProtoMessage() {}

func (x *RoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_interface_v1_demo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleReply.ProtoReflect.Descriptor instead.
func (*RoleReply) Descriptor() ([]byte, []int) {
	return file_interface_v1_demo_proto_rawDescGZIP(), []int{1}
}

func (x *RoleReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleReply) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

func (x *RoleReply) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type RoleListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	PageNo        int32                  `protobuf:"varint,2,opt,name=page_no,json=pageNo,proto3" json:"page_no,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	RoleList      []*RoleReply           `protobuf:"bytes,4,rep,name=roleList,proto3" json:"roleList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleListReply) Reset() {
	*x = RoleListReply{}
	mi := &file_interface_v1_demo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleListReply) ProtoMessage() {}

func (x *RoleListReply) ProtoReflect() protoreflect.Message {
	mi := &file_interface_v1_demo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleListReply.ProtoReflect.Descriptor instead.
func (*RoleListReply) Descriptor() ([]byte, []int) {
	return file_interface_v1_demo_proto_rawDescGZIP(), []int{2}
}

func (x *RoleListReply) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *RoleListReply) GetPageNo() int32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *RoleListReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *RoleListReply) GetRoleList() []*RoleReply {
	if x != nil {
		return x.RoleList
	}
	return nil
}

var File_interface_v1_demo_proto protoreflect.FileDescriptor

const file_interface_v1_demo_proto_rawDesc = "" +
	"\n" +
	"\x17interface/v1/demo.proto\x12\x10api.interface.v1\x1a\x1cgoogle/api/annotations.proto\"\xaf\x01\n" +
	"\x0fRoleListRequest\x12\x16\n" +
	"\x06pageNo\x18\x01 \x01(\x03R\x06pageNo\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\tR\x04sort\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\x12\x1a\n" +
	"\broleCode\x18\x05 \x01(\tR\broleCode\x12\x1a\n" +
	"\broleName\x18\x06 \x01(\tR\broleName\"S\n" +
	"\tRoleReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\broleCode\x18\x02 \x01(\tR\broleCode\x12\x1a\n" +
	"\broleName\x18\x03 \x01(\tR\broleName\"\x94\x01\n" +
	"\rRoleListReply\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\x12\x17\n" +
	"\apage_no\x18\x02 \x01(\x05R\x06pageNo\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x127\n" +
	"\broleList\x18\x04 \x03(\v2\x1b.api.interface.v1.RoleReplyR\broleList2m\n" +
	"\x04Demo\x12e\n" +
	"\bListPage\x12!.api.interface.v1.RoleListRequest\x1a\x1f.api.interface.v1.RoleListReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/role/listBC\n" +
	"\x10api.interface.v1P\x01Z-example.com/xxx/interface/api/interface/v1;v1b\x06proto3"

var (
	file_interface_v1_demo_proto_rawDescOnce sync.Once
	file_interface_v1_demo_proto_rawDescData []byte
)

func file_interface_v1_demo_proto_rawDescGZIP() []byte {
	file_interface_v1_demo_proto_rawDescOnce.Do(func() {
		file_interface_v1_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_interface_v1_demo_proto_rawDesc), len(file_interface_v1_demo_proto_rawDesc)))
	})
	return file_interface_v1_demo_proto_rawDescData
}

var file_interface_v1_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_interface_v1_demo_proto_goTypes = []any{
	(*RoleListRequest)(nil), // 0: api.interface.v1.RoleListRequest
	(*RoleReply)(nil),       // 1: api.interface.v1.RoleReply
	(*RoleListReply)(nil),   // 2: api.interface.v1.RoleListReply
}
var file_interface_v1_demo_proto_depIdxs = []int32{
	1, // 0: api.interface.v1.RoleListReply.roleList:type_name -> api.interface.v1.RoleReply
	0, // 1: api.interface.v1.Demo.ListPage:input_type -> api.interface.v1.RoleListRequest
	2, // 2: api.interface.v1.Demo.ListPage:output_type -> api.interface.v1.RoleListReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_interface_v1_demo_proto_init() }
func file_interface_v1_demo_proto_init() {
	if File_interface_v1_demo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_interface_v1_demo_proto_rawDesc), len(file_interface_v1_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_interface_v1_demo_proto_goTypes,
		DependencyIndexes: file_interface_v1_demo_proto_depIdxs,
		MessageInfos:      file_interface_v1_demo_proto_msgTypes,
	}.Build()
	File_interface_v1_demo_proto = out.File
	file_interface_v1_demo_proto_goTypes = nil
	file_interface_v1_demo_proto_depIdxs = nil
}
