// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.4
// source: user/v1/error_reason.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_USER_NOT_FOUND  ErrorReason = 0
	ErrorReason_CONTENT_MISSING ErrorReason = 1
	ErrorReason_NoLogin         ErrorReason = 2
	ErrorReason_Unauthorized    ErrorReason = 3
	ErrorReason_SignVerifyError ErrorReason = 4
	ErrorReason_SysError        ErrorReason = 5
	ErrorReason_ParamError      ErrorReason = 6
	ErrorReason_DBError         ErrorReason = 7
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "USER_NOT_FOUND",
		1: "CONTENT_MISSING",
		2: "NoLogin",
		3: "Unauthorized",
		4: "SignVerifyError",
		5: "SysError",
		6: "ParamError",
		7: "DBError",
	}
	ErrorReason_value = map[string]int32{
		"USER_NOT_FOUND":  0,
		"CONTENT_MISSING": 1,
		"NoLogin":         2,
		"Unauthorized":    3,
		"SignVerifyError": 4,
		"SysError":        5,
		"ParamError":      6,
		"DBError":         7,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_user_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_user_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_user_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_user_v1_error_reason_proto protoreflect.FileDescriptor

const file_user_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1auser/v1/error_reason.proto\x12\x11api.helloworld.v1\x1a\x13errors/errors.proto*\xcb\x01\n" +
	"\vErrorReason\x12\x18\n" +
	"\x0eUSER_NOT_FOUND\x10\x00\x1a\x04\xa8E\x94\x03\x12\x19\n" +
	"\x0fCONTENT_MISSING\x10\x01\x1a\x04\xa8E\x90\x03\x12\x11\n" +
	"\aNoLogin\x10\x02\x1a\x04\xa8E\x91\x03\x12\x16\n" +
	"\fUnauthorized\x10\x03\x1a\x04\xa8E\x92\x03\x12\x19\n" +
	"\x0fSignVerifyError\x10\x04\x1a\x04\xa8E\x93\x03\x12\x12\n" +
	"\bSysError\x10\x05\x1a\x04\xa8E\xf4\x03\x12\x14\n" +
	"\n" +
	"ParamError\x10\x06\x1a\x04\xa8E\xf5\x03\x12\x11\n" +
	"\aDBError\x10\a\x1a\x04\xa8E\xf6\x03\x1a\x04\xa0E\xf4\x03B<\n" +
	"\vapi.user.v1P\x01Z+example.com/xxx/user-service/api/user/v1;v1b\x06proto3"

var (
	file_user_v1_error_reason_proto_rawDescOnce sync.Once
	file_user_v1_error_reason_proto_rawDescData []byte
)

func file_user_v1_error_reason_proto_rawDescGZIP() []byte {
	file_user_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_user_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_error_reason_proto_rawDesc), len(file_user_v1_error_reason_proto_rawDesc)))
	})
	return file_user_v1_error_reason_proto_rawDescData
}

var file_user_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: api.helloworld.v1.ErrorReason
}
var file_user_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_v1_error_reason_proto_init() }
func file_user_v1_error_reason_proto_init() {
	if File_user_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_error_reason_proto_rawDesc), len(file_user_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_user_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_user_v1_error_reason_proto_enumTypes,
	}.Build()
	File_user_v1_error_reason_proto = out.File
	file_user_v1_error_reason_proto_goTypes = nil
	file_user_v1_error_reason_proto_depIdxs = nil
}
