// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.4
// source: api/user/v1/file.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileAddRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 文件路径(保存后路径)
	FilePath string `protobuf:"bytes,1,opt,name=filePath,proto3" json:"filePath,omitempty"`
	// 文件大小(字节)
	FileSize int64 `protobuf:"varint,2,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	// 文件md5
	FileMd5 string `protobuf:"bytes,3,opt,name=fileMd5,proto3" json:"fileMd5,omitempty"`
	// 媒介类型：image/jpeg 等
	MediaType string `protobuf:"bytes,4,opt,name=mediaType,proto3" json:"mediaType,omitempty"`
	// 原始文件名
	OriginalName string `protobuf:"bytes,5,opt,name=originalName,proto3" json:"originalName,omitempty"`
	// 创建时间
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// 更新时间
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	// 创建人
	CreatedBy string `protobuf:"bytes,8,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	// 更新人
	UpdatedBy     string `protobuf:"bytes,9,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileAddRequest) Reset() {
	*x = FileAddRequest{}
	mi := &file_api_user_v1_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileAddRequest) ProtoMessage() {}

func (x *FileAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileAddRequest.ProtoReflect.Descriptor instead.
func (*FileAddRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_file_proto_rawDescGZIP(), []int{0}
}

func (x *FileAddRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FileAddRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *FileAddRequest) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

func (x *FileAddRequest) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *FileAddRequest) GetOriginalName() string {
	if x != nil {
		return x.OriginalName
	}
	return ""
}

func (x *FileAddRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FileAddRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *FileAddRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *FileAddRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type FileAddReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 文件ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 文件路径(保存后路径)
	FilePath string `protobuf:"bytes,2,opt,name=filePath,proto3" json:"filePath,omitempty"`
	// 文件大小(字节)
	FileSize int64 `protobuf:"varint,3,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	// 文件md5
	FileMd5 string `protobuf:"bytes,4,opt,name=fileMd5,proto3" json:"fileMd5,omitempty"`
	// 媒介类型：image/jpeg 等
	MediaType string `protobuf:"bytes,5,opt,name=mediaType,proto3" json:"mediaType,omitempty"`
	// 原始文件名
	OriginalName  string `protobuf:"bytes,6,opt,name=originalName,proto3" json:"originalName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileAddReply) Reset() {
	*x = FileAddReply{}
	mi := &file_api_user_v1_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileAddReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileAddReply) ProtoMessage() {}

func (x *FileAddReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileAddReply.ProtoReflect.Descriptor instead.
func (*FileAddReply) Descriptor() ([]byte, []int) {
	return file_api_user_v1_file_proto_rawDescGZIP(), []int{1}
}

func (x *FileAddReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FileAddReply) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FileAddReply) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *FileAddReply) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

func (x *FileAddReply) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *FileAddReply) GetOriginalName() string {
	if x != nil {
		return x.OriginalName
	}
	return ""
}

var File_api_user_v1_file_proto protoreflect.FileDescriptor

const file_api_user_v1_file_proto_rawDesc = "" +
	"\n" +
	"\x16api/user/v1/file.proto\x12\vapi.user.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x02\n" +
	"\x0eFileAddRequest\x12\x1a\n" +
	"\bfilePath\x18\x01 \x01(\tR\bfilePath\x12\x1a\n" +
	"\bfileSize\x18\x02 \x01(\x03R\bfileSize\x12\x18\n" +
	"\afileMd5\x18\x03 \x01(\tR\afileMd5\x12\x1c\n" +
	"\tmediaType\x18\x04 \x01(\tR\tmediaType\x12\"\n" +
	"\foriginalName\x18\x05 \x01(\tR\foriginalName\x128\n" +
	"\tcreatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1c\n" +
	"\tcreatedBy\x18\b \x01(\tR\tcreatedBy\x12\x1c\n" +
	"\tupdatedBy\x18\t \x01(\tR\tupdatedBy\"\xb2\x01\n" +
	"\fFileAddReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bfilePath\x18\x02 \x01(\tR\bfilePath\x12\x1a\n" +
	"\bfileSize\x18\x03 \x01(\x03R\bfileSize\x12\x18\n" +
	"\afileMd5\x18\x04 \x01(\tR\afileMd5\x12\x1c\n" +
	"\tmediaType\x18\x05 \x01(\tR\tmediaType\x12\"\n" +
	"\foriginalName\x18\x06 \x01(\tR\foriginalName2G\n" +
	"\x04File\x12?\n" +
	"\x03Add\x12\x1b.api.user.v1.FileAddRequest\x1a\x19.api.user.v1.FileAddReply\"\x00B<\n" +
	"\vapi.user.v1P\x01Z+example.com/xxx/user-service/api/user/v1;v1b\x06proto3"

var (
	file_api_user_v1_file_proto_rawDescOnce sync.Once
	file_api_user_v1_file_proto_rawDescData []byte
)

func file_api_user_v1_file_proto_rawDescGZIP() []byte {
	file_api_user_v1_file_proto_rawDescOnce.Do(func() {
		file_api_user_v1_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_user_v1_file_proto_rawDesc), len(file_api_user_v1_file_proto_rawDesc)))
	})
	return file_api_user_v1_file_proto_rawDescData
}

var file_api_user_v1_file_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_user_v1_file_proto_goTypes = []any{
	(*FileAddRequest)(nil),        // 0: api.user.v1.FileAddRequest
	(*FileAddReply)(nil),          // 1: api.user.v1.FileAddReply
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_api_user_v1_file_proto_depIdxs = []int32{
	2, // 0: api.user.v1.FileAddRequest.createdAt:type_name -> google.protobuf.Timestamp
	2, // 1: api.user.v1.FileAddRequest.updatedAt:type_name -> google.protobuf.Timestamp
	0, // 2: api.user.v1.File.Add:input_type -> api.user.v1.FileAddRequest
	1, // 3: api.user.v1.File.Add:output_type -> api.user.v1.FileAddReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_user_v1_file_proto_init() }
func file_api_user_v1_file_proto_init() {
	if File_api_user_v1_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_v1_file_proto_rawDesc), len(file_api_user_v1_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_user_v1_file_proto_goTypes,
		DependencyIndexes: file_api_user_v1_file_proto_depIdxs,
		MessageInfos:      file_api_user_v1_file_proto_msgTypes,
	}.Build()
	File_api_user_v1_file_proto = out.File
	file_api_user_v1_file_proto_goTypes = nil
	file_api_user_v1_file_proto_depIdxs = nil
}
