// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.4
// source: user/v1/permission.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PermListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNo        int64                  `protobuf:"varint,1,opt,name=pageNo,proto3" json:"pageNo,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Sort          string                 `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Direction     string                 `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	PermName      string                 `protobuf:"bytes,5,opt,name=permName,proto3" json:"permName,omitempty"`
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	Action        string                 `protobuf:"bytes,7,opt,name=action,proto3" json:"action,omitempty"`
	PermType      int32                  `protobuf:"varint,8,opt,name=permType,proto3" json:"permType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermListRequest) Reset() {
	*x = PermListRequest{}
	mi := &file_user_v1_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermListRequest) ProtoMessage() {}

func (x *PermListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermListRequest.ProtoReflect.Descriptor instead.
func (*PermListRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_permission_proto_rawDescGZIP(), []int{0}
}

func (x *PermListRequest) GetPageNo() int64 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *PermListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PermListRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *PermListRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *PermListRequest) GetPermName() string {
	if x != nil {
		return x.PermName
	}
	return ""
}

func (x *PermListRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PermListRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PermListRequest) GetPermType() int32 {
	if x != nil {
		return x.PermType
	}
	return 0
}

type PermReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PermName      string                 `protobuf:"bytes,2,opt,name=permName,proto3" json:"permName,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	PermType      int32                  `protobuf:"varint,5,opt,name=permType,proto3" json:"permType,omitempty"`
	ParentId      int64                  `protobuf:"varint,6,opt,name=parentId,proto3" json:"parentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermReply) Reset() {
	*x = PermReply{}
	mi := &file_user_v1_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermReply) ProtoMessage() {}

func (x *PermReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermReply.ProtoReflect.Descriptor instead.
func (*PermReply) Descriptor() ([]byte, []int) {
	return file_user_v1_permission_proto_rawDescGZIP(), []int{1}
}

func (x *PermReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PermReply) GetPermName() string {
	if x != nil {
		return x.PermName
	}
	return ""
}

func (x *PermReply) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PermReply) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PermReply) GetPermType() int32 {
	if x != nil {
		return x.PermType
	}
	return 0
}

func (x *PermReply) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type PermListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	PageNo        int32                  `protobuf:"varint,2,opt,name=page_no,json=pageNo,proto3" json:"page_no,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PermList      []*PermReply           `protobuf:"bytes,4,rep,name=permList,proto3" json:"permList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermListReply) Reset() {
	*x = PermListReply{}
	mi := &file_user_v1_permission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermListReply) ProtoMessage() {}

func (x *PermListReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_permission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermListReply.ProtoReflect.Descriptor instead.
func (*PermListReply) Descriptor() ([]byte, []int) {
	return file_user_v1_permission_proto_rawDescGZIP(), []int{2}
}

func (x *PermListReply) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PermListReply) GetPageNo() int32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *PermListReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PermListReply) GetPermList() []*PermReply {
	if x != nil {
		return x.PermList
	}
	return nil
}

type PermSaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PermName      string                 `protobuf:"bytes,2,opt,name=permName,proto3" json:"permName,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	PermType      int32                  `protobuf:"varint,5,opt,name=permType,proto3" json:"permType,omitempty"`
	ParentId      int64                  `protobuf:"varint,6,opt,name=parentId,proto3" json:"parentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermSaveRequest) Reset() {
	*x = PermSaveRequest{}
	mi := &file_user_v1_permission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermSaveRequest) ProtoMessage() {}

func (x *PermSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_permission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermSaveRequest.ProtoReflect.Descriptor instead.
func (*PermSaveRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_permission_proto_rawDescGZIP(), []int{3}
}

func (x *PermSaveRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PermSaveRequest) GetPermName() string {
	if x != nil {
		return x.PermName
	}
	return ""
}

func (x *PermSaveRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PermSaveRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PermSaveRequest) GetPermType() int32 {
	if x != nil {
		return x.PermType
	}
	return 0
}

func (x *PermSaveRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

var File_user_v1_permission_proto protoreflect.FileDescriptor

const file_user_v1_permission_proto_rawDesc = "" +
	"\n" +
	"\x18user/v1/permission.proto\x12\x11api.helloworld.v1\x1a\x1cgoogle/api/annotations.proto\"\xd9\x01\n" +
	"\x0fPermListRequest\x12\x16\n" +
	"\x06pageNo\x18\x01 \x01(\x03R\x06pageNo\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\tR\x04sort\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\x12\x1a\n" +
	"\bpermName\x18\x05 \x01(\tR\bpermName\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x16\n" +
	"\x06action\x18\a \x01(\tR\x06action\x12\x1a\n" +
	"\bpermType\x18\b \x01(\x05R\bpermType\"\x99\x01\n" +
	"\tPermReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bpermName\x18\x02 \x01(\tR\bpermName\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1a\n" +
	"\bpermType\x18\x05 \x01(\x05R\bpermType\x12\x1a\n" +
	"\bparentId\x18\x06 \x01(\x03R\bparentId\"\x95\x01\n" +
	"\rPermListReply\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\x12\x17\n" +
	"\apage_no\x18\x02 \x01(\x05R\x06pageNo\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x128\n" +
	"\bpermList\x18\x04 \x03(\v2\x1c.api.helloworld.v1.PermReplyR\bpermList\"\x9f\x01\n" +
	"\x0fPermSaveRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bpermName\x18\x02 \x01(\tR\bpermName\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1a\n" +
	"\bpermType\x18\x05 \x01(\x05R\bpermType\x12\x1a\n" +
	"\bparentId\x18\x06 \x01(\x03R\bparentId2\xc8\x02\n" +
	"\n" +
	"Permission\x12j\n" +
	"\bListPage\x12\".api.helloworld.v1.PermListRequest\x1a .api.helloworld.v1.PermListReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/permission/list\x12c\n" +
	"\x03Add\x12\".api.helloworld.v1.PermSaveRequest\x1a\x1c.api.helloworld.v1.PermReply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/permission/add\x12i\n" +
	"\x06Update\x12\".api.helloworld.v1.PermSaveRequest\x1a\x1c.api.helloworld.v1.PermReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/permission/updateB<\n" +
	"\vapi.user.v1P\x01Z+example.com/xxx/user-service/api/user/v1;v1b\x06proto3"

var (
	file_user_v1_permission_proto_rawDescOnce sync.Once
	file_user_v1_permission_proto_rawDescData []byte
)

func file_user_v1_permission_proto_rawDescGZIP() []byte {
	file_user_v1_permission_proto_rawDescOnce.Do(func() {
		file_user_v1_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_permission_proto_rawDesc), len(file_user_v1_permission_proto_rawDesc)))
	})
	return file_user_v1_permission_proto_rawDescData
}

var file_user_v1_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_user_v1_permission_proto_goTypes = []any{
	(*PermListRequest)(nil), // 0: api.helloworld.v1.PermListRequest
	(*PermReply)(nil),       // 1: api.helloworld.v1.PermReply
	(*PermListReply)(nil),   // 2: api.helloworld.v1.PermListReply
	(*PermSaveRequest)(nil), // 3: api.helloworld.v1.PermSaveRequest
}
var file_user_v1_permission_proto_depIdxs = []int32{
	1, // 0: api.helloworld.v1.PermListReply.permList:type_name -> api.helloworld.v1.PermReply
	0, // 1: api.helloworld.v1.Permission.ListPage:input_type -> api.helloworld.v1.PermListRequest
	3, // 2: api.helloworld.v1.Permission.Add:input_type -> api.helloworld.v1.PermSaveRequest
	3, // 3: api.helloworld.v1.Permission.Update:input_type -> api.helloworld.v1.PermSaveRequest
	2, // 4: api.helloworld.v1.Permission.ListPage:output_type -> api.helloworld.v1.PermListReply
	1, // 5: api.helloworld.v1.Permission.Add:output_type -> api.helloworld.v1.PermReply
	1, // 6: api.helloworld.v1.Permission.Update:output_type -> api.helloworld.v1.PermReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_v1_permission_proto_init() }
func file_user_v1_permission_proto_init() {
	if File_user_v1_permission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_permission_proto_rawDesc), len(file_user_v1_permission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_permission_proto_goTypes,
		DependencyIndexes: file_user_v1_permission_proto_depIdxs,
		MessageInfos:      file_user_v1_permission_proto_msgTypes,
	}.Build()
	File_user_v1_permission_proto = out.File
	file_user_v1_permission_proto_goTypes = nil
	file_user_v1_permission_proto_depIdxs = nil
}
