// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.4
// source: user/v1/role.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNo        int64                  `protobuf:"varint,1,opt,name=pageNo,proto3" json:"pageNo,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Sort          string                 `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Direction     string                 `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	RoleCode      string                 `protobuf:"bytes,5,opt,name=roleCode,proto3" json:"roleCode,omitempty"`
	RoleName      string                 `protobuf:"bytes,6,opt,name=roleName,proto3" json:"roleName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleListRequest) Reset() {
	*x = RoleListRequest{}
	mi := &file_user_v1_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleListRequest) ProtoMessage() {}

func (x *RoleListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleListRequest.ProtoReflect.Descriptor instead.
func (*RoleListRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_role_proto_rawDescGZIP(), []int{0}
}

func (x *RoleListRequest) GetPageNo() int64 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *RoleListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *RoleListRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *RoleListRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *RoleListRequest) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

func (x *RoleListRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type RoleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleCode      string                 `protobuf:"bytes,2,opt,name=roleCode,proto3" json:"roleCode,omitempty"`
	RoleName      string                 `protobuf:"bytes,3,opt,name=roleName,proto3" json:"roleName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleReply) Reset() {
	*x = RoleReply{}
	mi := &file_user_v1_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleReply) ProtoMessage() {}

func (x *RoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleReply.ProtoReflect.Descriptor instead.
func (*RoleReply) Descriptor() ([]byte, []int) {
	return file_user_v1_role_proto_rawDescGZIP(), []int{1}
}

func (x *RoleReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleReply) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

func (x *RoleReply) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type RoleListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	PageNo        int32                  `protobuf:"varint,2,opt,name=page_no,json=pageNo,proto3" json:"page_no,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	RoleList      []*RoleReply           `protobuf:"bytes,4,rep,name=roleList,proto3" json:"roleList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleListReply) Reset() {
	*x = RoleListReply{}
	mi := &file_user_v1_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleListReply) ProtoMessage() {}

func (x *RoleListReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleListReply.ProtoReflect.Descriptor instead.
func (*RoleListReply) Descriptor() ([]byte, []int) {
	return file_user_v1_role_proto_rawDescGZIP(), []int{2}
}

func (x *RoleListReply) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *RoleListReply) GetPageNo() int32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *RoleListReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *RoleListReply) GetRoleList() []*RoleReply {
	if x != nil {
		return x.RoleList
	}
	return nil
}

type RoleSaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleCode      string                 `protobuf:"bytes,2,opt,name=roleCode,proto3" json:"roleCode,omitempty"`
	RoleName      string                 `protobuf:"bytes,3,opt,name=roleName,proto3" json:"roleName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleSaveRequest) Reset() {
	*x = RoleSaveRequest{}
	mi := &file_user_v1_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleSaveRequest) ProtoMessage() {}

func (x *RoleSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleSaveRequest.ProtoReflect.Descriptor instead.
func (*RoleSaveRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_role_proto_rawDescGZIP(), []int{3}
}

func (x *RoleSaveRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleSaveRequest) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

func (x *RoleSaveRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type RoleCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleCode      string                 `protobuf:"bytes,1,opt,name=roleCode,proto3" json:"roleCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleCodeRequest) Reset() {
	*x = RoleCodeRequest{}
	mi := &file_user_v1_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleCodeRequest) ProtoMessage() {}

func (x *RoleCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleCodeRequest.ProtoReflect.Descriptor instead.
func (*RoleCodeRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_role_proto_rawDescGZIP(), []int{4}
}

func (x *RoleCodeRequest) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

type RoleAssignPermRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
	PermIdList    []int64                `protobuf:"varint,2,rep,packed,name=PermIdList,proto3" json:"PermIdList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleAssignPermRequest) Reset() {
	*x = RoleAssignPermRequest{}
	mi := &file_user_v1_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAssignPermRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAssignPermRequest) ProtoMessage() {}

func (x *RoleAssignPermRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAssignPermRequest.ProtoReflect.Descriptor instead.
func (*RoleAssignPermRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_role_proto_rawDescGZIP(), []int{5}
}

func (x *RoleAssignPermRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *RoleAssignPermRequest) GetPermIdList() []int64 {
	if x != nil {
		return x.PermIdList
	}
	return nil
}

type RoleDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleDeleteRequest) Reset() {
	*x = RoleDeleteRequest{}
	mi := &file_user_v1_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleDeleteRequest) ProtoMessage() {}

func (x *RoleDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleDeleteRequest.ProtoReflect.Descriptor instead.
func (*RoleDeleteRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_role_proto_rawDescGZIP(), []int{6}
}

func (x *RoleDeleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RoleOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleOk) Reset() {
	*x = RoleOk{}
	mi := &file_user_v1_role_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleOk) ProtoMessage() {}

func (x *RoleOk) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_role_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleOk.ProtoReflect.Descriptor instead.
func (*RoleOk) Descriptor() ([]byte, []int) {
	return file_user_v1_role_proto_rawDescGZIP(), []int{7}
}

func (x *RoleOk) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_user_v1_role_proto protoreflect.FileDescriptor

const file_user_v1_role_proto_rawDesc = "" +
	"\n" +
	"\x12user/v1/role.proto\x12\vapi.user.v1\x1a\x1cgoogle/api/annotations.proto\"\xaf\x01\n" +
	"\x0fRoleListRequest\x12\x16\n" +
	"\x06pageNo\x18\x01 \x01(\x03R\x06pageNo\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\tR\x04sort\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\x12\x1a\n" +
	"\broleCode\x18\x05 \x01(\tR\broleCode\x12\x1a\n" +
	"\broleName\x18\x06 \x01(\tR\broleName\"S\n" +
	"\tRoleReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\broleCode\x18\x02 \x01(\tR\broleCode\x12\x1a\n" +
	"\broleName\x18\x03 \x01(\tR\broleName\"\x8f\x01\n" +
	"\rRoleListReply\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\x12\x17\n" +
	"\apage_no\x18\x02 \x01(\x05R\x06pageNo\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x122\n" +
	"\broleList\x18\x04 \x03(\v2\x16.api.user.v1.RoleReplyR\broleList\"Y\n" +
	"\x0fRoleSaveRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\broleCode\x18\x02 \x01(\tR\broleCode\x12\x1a\n" +
	"\broleName\x18\x03 \x01(\tR\broleName\"-\n" +
	"\x0fRoleCodeRequest\x12\x1a\n" +
	"\broleCode\x18\x01 \x01(\tR\broleCode\"O\n" +
	"\x15RoleAssignPermRequest\x12\x16\n" +
	"\x06RoleId\x18\x01 \x01(\x03R\x06RoleId\x12\x1e\n" +
	"\n" +
	"PermIdList\x18\x02 \x03(\x03R\n" +
	"PermIdList\"#\n" +
	"\x11RoleDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\"\n" +
	"\x06RoleOk\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xdf\x03\n" +
	"\x04Role\x12[\n" +
	"\bListPage\x12\x1c.api.user.v1.RoleListRequest\x1a\x1a.api.user.v1.RoleListReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/role/list\x12T\n" +
	"\x03Add\x12\x1c.api.user.v1.RoleSaveRequest\x1a\x16.api.user.v1.RoleReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/role/add\x12X\n" +
	"\tGetByCode\x12\x1c.api.user.v1.RoleCodeRequest\x1a\x16.api.user.v1.RoleReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/role/code\x12k\n" +
	"\x10AssignPermission\x12\".api.user.v1.RoleAssignPermRequest\x1a\x13.api.user.v1.RoleOk\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/role/assignPerm\x12]\n" +
	"\n" +
	"DeleteById\x12\x1e.api.user.v1.RoleDeleteRequest\x1a\x13.api.user.v1.RoleOk\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/role/deleteB<\n" +
	"\vapi.user.v1P\x01Z+example.com/xxx/user-service/api/user/v1;v1b\x06proto3"

var (
	file_user_v1_role_proto_rawDescOnce sync.Once
	file_user_v1_role_proto_rawDescData []byte
)

func file_user_v1_role_proto_rawDescGZIP() []byte {
	file_user_v1_role_proto_rawDescOnce.Do(func() {
		file_user_v1_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_role_proto_rawDesc), len(file_user_v1_role_proto_rawDesc)))
	})
	return file_user_v1_role_proto_rawDescData
}

var file_user_v1_role_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_user_v1_role_proto_goTypes = []any{
	(*RoleListRequest)(nil),       // 0: api.user.v1.RoleListRequest
	(*RoleReply)(nil),             // 1: api.user.v1.RoleReply
	(*RoleListReply)(nil),         // 2: api.user.v1.RoleListReply
	(*RoleSaveRequest)(nil),       // 3: api.user.v1.RoleSaveRequest
	(*RoleCodeRequest)(nil),       // 4: api.user.v1.RoleCodeRequest
	(*RoleAssignPermRequest)(nil), // 5: api.user.v1.RoleAssignPermRequest
	(*RoleDeleteRequest)(nil),     // 6: api.user.v1.RoleDeleteRequest
	(*RoleOk)(nil),                // 7: api.user.v1.RoleOk
}
var file_user_v1_role_proto_depIdxs = []int32{
	1, // 0: api.user.v1.RoleListReply.roleList:type_name -> api.user.v1.RoleReply
	0, // 1: api.user.v1.Role.ListPage:input_type -> api.user.v1.RoleListRequest
	3, // 2: api.user.v1.Role.Add:input_type -> api.user.v1.RoleSaveRequest
	4, // 3: api.user.v1.Role.GetByCode:input_type -> api.user.v1.RoleCodeRequest
	5, // 4: api.user.v1.Role.AssignPermission:input_type -> api.user.v1.RoleAssignPermRequest
	6, // 5: api.user.v1.Role.DeleteById:input_type -> api.user.v1.RoleDeleteRequest
	2, // 6: api.user.v1.Role.ListPage:output_type -> api.user.v1.RoleListReply
	1, // 7: api.user.v1.Role.Add:output_type -> api.user.v1.RoleReply
	1, // 8: api.user.v1.Role.GetByCode:output_type -> api.user.v1.RoleReply
	7, // 9: api.user.v1.Role.AssignPermission:output_type -> api.user.v1.RoleOk
	7, // 10: api.user.v1.Role.DeleteById:output_type -> api.user.v1.RoleOk
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_v1_role_proto_init() }
func file_user_v1_role_proto_init() {
	if File_user_v1_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_role_proto_rawDesc), len(file_user_v1_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_role_proto_goTypes,
		DependencyIndexes: file_user_v1_role_proto_depIdxs,
		MessageInfos:      file_user_v1_role_proto_msgTypes,
	}.Build()
	File_user_v1_role_proto = out.File
	file_user_v1_role_proto_goTypes = nil
	file_user_v1_role_proto_depIdxs = nil
}
