// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.4
// source: user/v1/user.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户列表查询条件
type UserListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 当前页数
	PageNo int64 `protobuf:"varint,1,opt,name=pageNo,proto3" json:"pageNo,omitempty"`
	// 每页数量
	PageSize int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	// 排序字段
	Sort string `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	// 排序类型：asc、desc
	Direction string `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	// 姓名
	RealName string `protobuf:"bytes,5,opt,name=realName,proto3" json:"realName,omitempty"`
	// 邮箱
	Email string `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	// 状态
	Status        int32 `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListRequest) Reset() {
	*x = UserListRequest{}
	mi := &file_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListRequest) ProtoMessage() {}

func (x *UserListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListRequest.ProtoReflect.Descriptor instead.
func (*UserListRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserListRequest) GetPageNo() int64 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *UserListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *UserListRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *UserListRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *UserListRequest) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *UserListRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserListRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 用户信息
type UserReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 姓名
	RealName string `protobuf:"bytes,2,opt,name=realName,proto3" json:"realName,omitempty"`
	// 用户名
	UserName string `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	// 邮箱
	Email string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	// 状态
	Status int32 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	// 角色
	RoleCode      string `protobuf:"bytes,6,opt,name=roleCode,proto3" json:"roleCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReply) Reset() {
	*x = UserReply{}
	mi := &file_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReply) ProtoMessage() {}

func (x *UserReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReply.ProtoReflect.Descriptor instead.
func (*UserReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserReply) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *UserReply) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserReply) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserReply) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

// 用户列表
type UserListReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 总数量
	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// 当前页
	PageNo int32 `protobuf:"varint,2,opt,name=page_no,json=pageNo,proto3" json:"page_no,omitempty"`
	// 每页数
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// 用户例表
	UserList      []*UserReply `protobuf:"bytes,4,rep,name=userList,proto3" json:"userList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListReply) Reset() {
	*x = UserListReply{}
	mi := &file_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListReply) ProtoMessage() {}

func (x *UserListReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListReply.ProtoReflect.Descriptor instead.
func (*UserListReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserListReply) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *UserListReply) GetPageNo() int32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *UserListReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *UserListReply) GetUserList() []*UserReply {
	if x != nil {
		return x.UserList
	}
	return nil
}

// 用户邮箱信息
type UserEmailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 邮箱
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// 密码
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserEmailRequest) Reset() {
	*x = UserEmailRequest{}
	mi := &file_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEmailRequest) ProtoMessage() {}

func (x *UserEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEmailRequest.ProtoReflect.Descriptor instead.
func (*UserEmailRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserEmailRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 邮箱登录
type UserEmailLoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 邮箱
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// 密码
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserEmailLoginRequest) Reset() {
	*x = UserEmailLoginRequest{}
	mi := &file_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserEmailLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEmailLoginRequest) ProtoMessage() {}

func (x *UserEmailLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEmailLoginRequest.ProtoReflect.Descriptor instead.
func (*UserEmailLoginRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserEmailLoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserEmailLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 登录响应
type LoginReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 分配角色
type AssignRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	// 角色编号
	RoleCode      string `protobuf:"bytes,2,opt,name=roleCode,proto3" json:"roleCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleRequest) Reset() {
	*x = AssignRoleRequest{}
	mi := &file_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleRequest) ProtoMessage() {}

func (x *AssignRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleRequest.ProtoReflect.Descriptor instead.
func (*AssignRoleRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *AssignRoleRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AssignRoleRequest) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

type UserOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOk) Reset() {
	*x = UserOk{}
	mi := &file_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOk) ProtoMessage() {}

func (x *UserOk) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOk.ProtoReflect.Descriptor instead.
func (*UserOk) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserOk) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UserDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDeleteRequest) Reset() {
	*x = UserDeleteRequest{}
	mi := &file_user_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeleteRequest) ProtoMessage() {}

func (x *UserDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeleteRequest.ProtoReflect.Descriptor instead.
func (*UserDeleteRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserDeleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CheckPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sub           string                 `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	Obj           string                 `protobuf:"bytes,2,opt,name=obj,proto3" json:"obj,omitempty"`
	Act           string                 `protobuf:"bytes,3,opt,name=act,proto3" json:"act,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionRequest) Reset() {
	*x = CheckPermissionRequest{}
	mi := &file_user_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionRequest) ProtoMessage() {}

func (x *CheckPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *CheckPermissionRequest) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *CheckPermissionRequest) GetObj() string {
	if x != nil {
		return x.Obj
	}
	return ""
}

func (x *CheckPermissionRequest) GetAct() string {
	if x != nil {
		return x.Act
	}
	return ""
}

type UserVerifyTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserVerifyTokenRequest) Reset() {
	*x = UserVerifyTokenRequest{}
	mi := &file_user_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserVerifyTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserVerifyTokenRequest) ProtoMessage() {}

func (x *UserVerifyTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserVerifyTokenRequest.ProtoReflect.Descriptor instead.
func (*UserVerifyTokenRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *UserVerifyTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UserClaimsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sub           string                 `protobuf:"bytes,2,opt,name=sub,proto3" json:"sub,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserClaimsReply) Reset() {
	*x = UserClaimsReply{}
	mi := &file_user_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserClaimsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserClaimsReply) ProtoMessage() {}

func (x *UserClaimsReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserClaimsReply.ProtoReflect.Descriptor instead.
func (*UserClaimsReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *UserClaimsReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserClaimsReply) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *UserClaimsReply) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_user_v1_user_proto protoreflect.FileDescriptor

const file_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x12user/v1/user.proto\x12\x11api.helloworld.v1\x1a\x1cgoogle/api/annotations.proto\"\xc1\x01\n" +
	"\x0fUserListRequest\x12\x16\n" +
	"\x06pageNo\x18\x01 \x01(\x03R\x06pageNo\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\tR\x04sort\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\x12\x1a\n" +
	"\brealName\x18\x05 \x01(\tR\brealName\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\"\x9d\x01\n" +
	"\tUserReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\brealName\x18\x02 \x01(\tR\brealName\x12\x1a\n" +
	"\buserName\x18\x03 \x01(\tR\buserName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1a\n" +
	"\broleCode\x18\x06 \x01(\tR\broleCode\"\x95\x01\n" +
	"\rUserListReply\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\x12\x17\n" +
	"\apage_no\x18\x02 \x01(\x05R\x06pageNo\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x128\n" +
	"\buserList\x18\x04 \x03(\v2\x1c.api.helloworld.v1.UserReplyR\buserList\"D\n" +
	"\x10UserEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"I\n" +
	"\x15UserEmailLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\"\n" +
	"\n" +
	"LoginReply\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"G\n" +
	"\x11AssignRoleRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\broleCode\x18\x02 \x01(\tR\broleCode\"\"\n" +
	"\x06UserOk\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"#\n" +
	"\x11UserDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"N\n" +
	"\x16CheckPermissionRequest\x12\x10\n" +
	"\x03sub\x18\x01 \x01(\tR\x03sub\x12\x10\n" +
	"\x03obj\x18\x02 \x01(\tR\x03obj\x12\x10\n" +
	"\x03act\x18\x03 \x01(\tR\x03act\".\n" +
	"\x16UserVerifyTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"G\n" +
	"\x0fUserClaimsReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03sub\x18\x02 \x01(\tR\x03sub\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role2\x9c\x06\n" +
	"\x04User\x12d\n" +
	"\bListPage\x12\".api.helloworld.v1.UserListRequest\x1a .api.helloworld.v1.UserListReply\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/user/list\x12r\n" +
	"\rCreateByEmail\x12#.api.helloworld.v1.UserEmailRequest\x1a\x1c.api.helloworld.v1.UserReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/user/createByEmail\x12o\n" +
	"\fLoginByEmail\x12(.api.helloworld.v1.UserEmailLoginRequest\x1a\x1d.api.helloworld.v1.LoginReply\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/user/login\x12j\n" +
	"\n" +
	"AssignRole\x12$.api.helloworld.v1.AssignRoleRequest\x1a\x19.api.helloworld.v1.UserOk\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/user/assignRole\x12f\n" +
	"\n" +
	"DeleteById\x12$.api.helloworld.v1.UserDeleteRequest\x1a\x19.api.helloworld.v1.UserOk\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/user/delete\x12y\n" +
	"\x0fCheckPermission\x12).api.helloworld.v1.CheckPermissionRequest\x1a\x19.api.helloworld.v1.UserOk\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/user/checkPermission\x12z\n" +
	"\vVerifyToken\x12).api.helloworld.v1.UserVerifyTokenRequest\x1a\".api.helloworld.v1.UserClaimsReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/user/verifyTokenBB\n" +
	"\x11api.helloworld.v1P\x01Z+example.com/xxx/user-service/api/user/v1;v1b\x06proto3"

var (
	file_user_v1_user_proto_rawDescOnce sync.Once
	file_user_v1_user_proto_rawDescData []byte
)

func file_user_v1_user_proto_rawDescGZIP() []byte {
	file_user_v1_user_proto_rawDescOnce.Do(func() {
		file_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)))
	})
	return file_user_v1_user_proto_rawDescData
}

var file_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_user_v1_user_proto_goTypes = []any{
	(*UserListRequest)(nil),        // 0: api.helloworld.v1.UserListRequest
	(*UserReply)(nil),              // 1: api.helloworld.v1.UserReply
	(*UserListReply)(nil),          // 2: api.helloworld.v1.UserListReply
	(*UserEmailRequest)(nil),       // 3: api.helloworld.v1.UserEmailRequest
	(*UserEmailLoginRequest)(nil),  // 4: api.helloworld.v1.UserEmailLoginRequest
	(*LoginReply)(nil),             // 5: api.helloworld.v1.LoginReply
	(*AssignRoleRequest)(nil),      // 6: api.helloworld.v1.AssignRoleRequest
	(*UserOk)(nil),                 // 7: api.helloworld.v1.UserOk
	(*UserDeleteRequest)(nil),      // 8: api.helloworld.v1.UserDeleteRequest
	(*CheckPermissionRequest)(nil), // 9: api.helloworld.v1.CheckPermissionRequest
	(*UserVerifyTokenRequest)(nil), // 10: api.helloworld.v1.UserVerifyTokenRequest
	(*UserClaimsReply)(nil),        // 11: api.helloworld.v1.UserClaimsReply
}
var file_user_v1_user_proto_depIdxs = []int32{
	1,  // 0: api.helloworld.v1.UserListReply.userList:type_name -> api.helloworld.v1.UserReply
	0,  // 1: api.helloworld.v1.User.ListPage:input_type -> api.helloworld.v1.UserListRequest
	3,  // 2: api.helloworld.v1.User.CreateByEmail:input_type -> api.helloworld.v1.UserEmailRequest
	4,  // 3: api.helloworld.v1.User.LoginByEmail:input_type -> api.helloworld.v1.UserEmailLoginRequest
	6,  // 4: api.helloworld.v1.User.AssignRole:input_type -> api.helloworld.v1.AssignRoleRequest
	8,  // 5: api.helloworld.v1.User.DeleteById:input_type -> api.helloworld.v1.UserDeleteRequest
	9,  // 6: api.helloworld.v1.User.CheckPermission:input_type -> api.helloworld.v1.CheckPermissionRequest
	10, // 7: api.helloworld.v1.User.VerifyToken:input_type -> api.helloworld.v1.UserVerifyTokenRequest
	2,  // 8: api.helloworld.v1.User.ListPage:output_type -> api.helloworld.v1.UserListReply
	1,  // 9: api.helloworld.v1.User.CreateByEmail:output_type -> api.helloworld.v1.UserReply
	5,  // 10: api.helloworld.v1.User.LoginByEmail:output_type -> api.helloworld.v1.LoginReply
	7,  // 11: api.helloworld.v1.User.AssignRole:output_type -> api.helloworld.v1.UserOk
	7,  // 12: api.helloworld.v1.User.DeleteById:output_type -> api.helloworld.v1.UserOk
	7,  // 13: api.helloworld.v1.User.CheckPermission:output_type -> api.helloworld.v1.UserOk
	11, // 14: api.helloworld.v1.User.VerifyToken:output_type -> api.helloworld.v1.UserClaimsReply
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_user_v1_user_proto_init() }
func file_user_v1_user_proto_init() {
	if File_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_user_proto_goTypes,
		DependencyIndexes: file_user_v1_user_proto_depIdxs,
		MessageInfos:      file_user_v1_user_proto_msgTypes,
	}.Build()
	File_user_v1_user_proto = out.File
	file_user_v1_user_proto_goTypes = nil
	file_user_v1_user_proto_depIdxs = nil
}
