// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"example.com/xxx/interface/internal/biz"
	"example.com/xxx/interface/internal/conf"
	"example.com/xxx/interface/internal/data"
	"example.com/xxx/interface/internal/server"
	"example.com/xxx/interface/internal/service"
	"github.com/go-kratos/kratos/v2"
	"go.uber.org/zap"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger *zap.Logger) (*kratos.App, func(), error) {
	discovery := data.NewDiscovery(bootstrap)
	userClient := data.NewUserServiceClient(discovery)
	roleClient := data.NewRoleServiceClient(discovery)
	fileClient := data.NewFileServiceClient(discovery)
	dataData, cleanup, err := data.NewData(bootstrap, userClient, roleClient, fileClient)
	if err != nil {
		return nil, nil, err
	}
	demoRepo := data.NewDemoRepo(dataData)
	demoUseCase := biz.NewDemoUseCase(demoRepo)
	demoService := service.NewDemoService(demoUseCase)
	grpcServer := server.NewGRPCServer(bootstrap, userClient, demoService)
	fileRepo := data.NewFileRepo(dataData)
	fileUseCase := biz.NewFileUseCase(fileRepo)
	storage := data.NewStorage()
	fileService := service.NewFileService(fileUseCase, storage)
	httpServer := server.NewHTTPServer(bootstrap, userClient, demoService, fileService)
	registrar := data.NewRegistrar(bootstrap)
	app := newApp(grpcServer, httpServer, logger, registrar)
	return app, func() {
		cleanup()
	}, nil
}
